"""Independent version axes for package, wire container and suite families."""

PACKAGE_VERSION = "2.2.0a1"
CONTEXT_WIRE_VERSION = 2
DIGEST_WIRE_VERSION = 2
EVIDENCE_WIRE_VERSION = 2
KDF_PARAMETER_WIRE_VERSION = 2
KDF_RECORD_WIRE_VERSION = 2
POW_WIRE_VERSION = 3
SIGNED_COMMITMENT_WIRE_VERSION = 2
ACTIVE_SUITE_FAMILIES = ("v2-2",)
TRANSITIONAL_SUITE_FAMILIES: tuple[str, ...] = ()
SUPPORTED_SUITE_FAMILIES = ACTIVE_SUITE_FAMILIES

__all__ = [
    "ACTIVE_SUITE_FAMILIES",
    "CONTEXT_WIRE_VERSION",
    "DIGEST_WIRE_VERSION",
    "EVIDENCE_WIRE_VERSION",
    "KDF_PARAMETER_WIRE_VERSION",
    "KDF_RECORD_WIRE_VERSION",
    "PACKAGE_VERSION",
    "POW_WIRE_VERSION",
    "SIGNED_COMMITMENT_WIRE_VERSION",
    "SUPPORTED_SUITE_FAMILIES",
    "TRANSITIONAL_SUITE_FAMILIES",
]
