"""Stable identifiers for Sigma Artifact V1."""

from enum import IntEnum

from sigma.version import ARTIFACT_WIRE_VERSION

ARTIFACT_MAGIC = b"SIGARTF1"
ARTIFACT_IDENTITY_MAGIC = b"SIGAIDN1"
ARTIFACT_DESCRIPTOR_MAGIC = b"SIGADSC1"
ARTIFACT_ID_DOMAIN = b"SIGMA-ARTIFACT-ID-V1\x00"
MANIFEST_ID_DOMAIN = b"SIGMA-MANIFEST-ID-V1\x00"

MAX_ARTIFACT_PARENTS = 1024
MAX_ARTIFACT_NAME_BYTES = 4096
MAX_ARTIFACT_MEDIA_TYPE_BYTES = 255
MAX_ARTIFACT_RECORD_BODY = 4 * 1024 * 1024


class ArtifactProfileV1(IntEnum):
    TREE = 0x0001
    TRAJECTORY = 0x0002
    DUAL = 0x0003


class ArtifactDescriptorProfileV1(IntEnum):
    BASE_V1 = 0x0001


__all__ = [
    "ARTIFACT_DESCRIPTOR_MAGIC",
    "ARTIFACT_IDENTITY_MAGIC",
    "ARTIFACT_ID_DOMAIN",
    "ARTIFACT_MAGIC",
    "ARTIFACT_WIRE_VERSION",
    "ArtifactDescriptorProfileV1",
    "ArtifactProfileV1",
    "MANIFEST_ID_DOMAIN",
    "MAX_ARTIFACT_MEDIA_TYPE_BYTES",
    "MAX_ARTIFACT_NAME_BYTES",
    "MAX_ARTIFACT_PARENTS",
    "MAX_ARTIFACT_RECORD_BODY",
]
