"""Sigma ecosystem interoperability adapters."""

from .oci import (
    MAX_OCI_MANIFEST_BYTES,
    OCI_EMPTY_CONFIG_BYTES,
    OCI_EMPTY_CONFIG_DIGEST,
    OCI_EMPTY_CONFIG_MEDIA_TYPE,
    OCI_IMAGE_INDEX_MEDIA_TYPE,
    OCI_IMAGE_MANIFEST_MEDIA_TYPE,
    SIGMA_ARTIFACT_ID_ANNOTATION,
    SIGMA_ARTIFACT_MEDIA_TYPE,
    SIGMA_ARTIFACT_REFERRER_TYPE,
    SIGMA_WIRE_SHA256_ANNOTATION,
    OciArtifactBindingError,
    OciDescriptorV1,
    OciInteropError,
    OciManifestError,
    OciSigmaArtifactBindingV1,
    build_sigma_artifact_referrer_v1,
    oci_sha256_digest_v1,
    parse_sigma_referrers_index_v1,
    sigma_artifact_payload_descriptor_v1,
    verify_sigma_artifact_referrer_v1,
)

__all__ = [
    "MAX_OCI_MANIFEST_BYTES",
    "OCI_EMPTY_CONFIG_BYTES",
    "OCI_EMPTY_CONFIG_DIGEST",
    "OCI_EMPTY_CONFIG_MEDIA_TYPE",
    "OCI_IMAGE_INDEX_MEDIA_TYPE",
    "OCI_IMAGE_MANIFEST_MEDIA_TYPE",
    "SIGMA_ARTIFACT_ID_ANNOTATION",
    "SIGMA_ARTIFACT_MEDIA_TYPE",
    "SIGMA_ARTIFACT_REFERRER_TYPE",
    "SIGMA_WIRE_SHA256_ANNOTATION",
    "OciArtifactBindingError",
    "OciDescriptorV1",
    "OciInteropError",
    "OciManifestError",
    "OciSigmaArtifactBindingV1",
    "build_sigma_artifact_referrer_v1",
    "oci_sha256_digest_v1",
    "parse_sigma_referrers_index_v1",
    "sigma_artifact_payload_descriptor_v1",
    "verify_sigma_artifact_referrer_v1",
]
